name: Publish

on:
  release:
    types:
      - published

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: >-
          ./gradlew
          -Porg.gradle.java.installations.auto-download=false
          -DjavaLanguageVersion=1.8
          test
          build
          publish
        env:
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
